databaseChangeLog:
  - changeSet:
      id: 1
      author: Nikolay
      changes:
        - createTable:
            tableName: application
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: status
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: text
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: phone_number
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: bigint
                  constraints:
                    nullable: false
                    foreignKeyName: fk_application_user
                    referencedTableName: "users"
                    referencedColumnNames: id